# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Janela(object):
    def setupUi(self, Janela):
        Janela.setObjectName("Janela")
        Janela.resize(222, 86)
        self.centralwidget = QtWidgets.QWidget(Janela)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setObjectName("label_nome")
        self.verticalLayout.addWidget(self.label_nome)
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.verticalLayout.addWidget(self.lineEdit_nome)
        self.pushButton_confirmar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_confirmar.setObjectName("pushButton_confirmar")
        self.pushButton_confirmar.clicked.connect(self.confirmar)
        self.verticalLayout.addWidget(self.pushButton_confirmar)
        Janela.setCentralWidget(self.centralwidget)

        self.retranslateUi(Janela)
        QtCore.QMetaObject.connectSlotsByName(Janela)

    def retranslateUi(self, Janela):
        _translate = QtCore.QCoreApplication.translate
        Janela.setWindowTitle(_translate("Janela", "Programa Legal 1.0"))
        self.label_nome.setText(_translate("Janela", "Qual é o seu nome?"))
        self.pushButton_confirmar.setText(_translate("Janela", "Confirmar"))

    def confirmar(self):
        #captura o texto do componente
        nome = self.lineEdit_nome.text()
        
        #cria e exibe uma jenela com mensagem
        msg = QMessageBox()
        msg.setText(f"Seja bem vindo, {nome}!")
        msg.setWindowTitle("Aviso")
        msg.exec_()
        
        #print(f"Seja bem vindo, {nome}!")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Janela = QtWidgets.QMainWindow()
    ui = Ui_Janela()
    ui.setupUi(Janela)
    Janela.show()
    sys.exit(app.exec_())
